name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: Build Calculator (${{ matrix.target.os }})
    runs-on: ${{ matrix.target.host || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
          - os: windows
            ext: .exe
          - os: freebsd
          - os: android
            args: -app-id calc.${GITHUB_SHA}
          # - os: darwin
          #   args: -app-id calc.${GITHUB_SHA}
          #   host: macos-latest
          # - os: ios
          #   args: -app-id calc.${GITHUB_SHA}
          #   host: macos-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: fyne-io/fyne-cross
          path: fyne-cross
          ref: develop

      - name: Checkout calculator app
        uses: actions/checkout@v2
        with:
          repository: fyne-io/calculator
          path: calculator

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/fyne-cross
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/go.sum') }}

      - name: Install Fyne-cross
        working-directory: fyne-cross
        run: go install
        env:
          GOBIN: "/usr/local/bin/"

      - name: Build
        working-directory: calculator
        run: |
          fyne-cross \
            ${{ matrix.target.os }} \
            -debug -no-cache \
            ${{ matrix.target.args }} \
            -name calculator${{ matrix.target.ext }}
